= Employee App

A simple CRUD app written in nodejs.

== Running the app

Start the app with `node bin/www` (after `npm install`) or `npm start`. Navigate to http://localhost:3000.

== Deployment

Deployed to https://boiling-lake-47544.herokuapp.com/ (for now.)

== Developer Notes

=== Assumptions
. Body of the POST/PUT is a JSON object
. Names are exclusively latin alphanumeric characters (no spaces,dashes, etc.)
. Delete buttons should be implemented to remove employees (present in template but not mentioned in spec)
. Update button should be implemented to update existing employees (present in template but not mentioned in spec)
. Exhaustive error handling, client-side validation, and tests are outside the scope of this challenge

=== Picking a Framework

Quick search for node REST frameworks indicates that Express is still popular. I've meddled with that before so it seems like a reasonable choice.

I've used Heroku to deploy apps before, and they have decent tutorials - I'll start with their template. That will have a nice side effect of making the app easy to share.

=== Environment Setup

Which version of node do I want? Looks like consensus is take the latest "LTS" version, which is currently 14.x, but 16.x will be ready for primetime in October.
https://nodejs.org/en/about/releases/

=== Starter Code

Used ExpressJS Getting Started guide to boostrap an app:
https://expressjs.com/en/starter/installing.html

=== PUG Template Engine

This could be neat, but the spec implies that we should be updating the table client-side using REST calls.
Removing PUG to simplify process of writing dynamic front-end.

=== Known issues
. Redundant GET calls are made when updating the table (should only call once after all the PUTs)
.. There may also be some kind of race condition here - sometimes the table doesn't seem to update properly after a delete
. Throughout the code, I've left comments and "TODO" messages indicated potentially unresolved issues
or where additional polish would be desirable.

=== Potential Improvements
. Add unit tests of some kind
. Add client side validations
. Add some CSS

=== References
Many sites referenced for basic information & syntax, in particular:

. https://developer.mozilla.org
. https://stackoverflow.com/ (of course)

=== Final thoughts
. I enjoyed experimenting with JS.
It would be good to take a class to get some formal training/learn some good practices, especially on the front-end.
. I started fiddling around with using React on the front end (see 'react' branch), but it is unfinished.
